# Generated by Django 4.1.2 on 2022-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_about_user_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="book.jpg", null=True, upload_to=""),
        ),
    ]
